name: Upload Schema Artifact

on:
  release:
    types: [ published ]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Generate and Upload WPGraphQL for ACF Schema Artifact
    services:
      mariadb:
        image: mariadb:10.8.2
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        # Ensure docker waits for mariadb to start
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer, wp-cli

      - name: Install dependencies
        run: composer install --no-dev

      - name: Setup WordPress
        run: |
          composer run install-test-env
        env:
          ACF_LICENSE_KEY: ${{secrets.ACF_LICENSE_KEY}}

      - name: Install WP CLI for ACF
        run: |
          cd /tmp/wordpress/
          wp --allow-root plugin install https://github.com/hoppinger/advanced-custom-fields-wpcli/archive/refs/heads/master.zip --activate

      - name: Import test Field Group
        run: |
          cd /tmp/wordpress/
          wp --allow-root acf import --json_file="${GITHUB_WORKSPACE}/tests/_data/acf-basic-fields.json"

      - name: Generate the Static Schema
        run: |
          cd /tmp/wordpress/
          # Output: /tmp/schema.graphql
          wp --allow-root graphql generate-static-schema

      - name: Upload schema as release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/schema.graphql
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
